import 'package:myproject_app/models/ticket.dart';

class ListTicket {
  static final List<Ticket> veDiHCM = [
    Ticket(
      hanhTrinh: 'Cần Thơ -> Sài Gòn',
      maHanhTrinh: 'ct-hcm',
      gioKhoiHanhHienThi: '9:55 sáng',
      gioKhoiHanhSoSanh: '09:55:00.000000',
      diemDi: 'Bến xe 91B',
      giaVe: 165000,
      khoanCach: '160 km',
      diemDen: 'Bến xe Miền Tây',
      soGhe: 16,
      dcDiemDi: 'QL 91B (Nguyễn Văn Linh), Hưng Lợi, Ninh Kiều, Tp Cần Thơ',
      dcDiemDen: '395 Kinh Đ. Vương, An Lạc, Bình Tân, Tp HCM',
      thoiGianDuKien: 4,
      loaiChuyenXe: 'veDiHCM',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Đà lạt -> Sài Gòn',
      maHanhTrinh: 'dl-hcm',
      gioKhoiHanhHienThi: '14:30 chiều',
      gioKhoiHanhSoSanh: '14:30:00.000000',
      diemDen: 'Bến xe Miền Đông mới',
      giaVe: 300000,
      khoanCach: '310 km',
      diemDi: 'Bến xe Đà Lạt',
      soGhe: 16,
      dcDiemDen: '501 Hoàng Hữu Nam, p. Long Bình, TP Thủ Đức',
      dcDiemDi: '1 Tô Hiến Thành, Phường 3, Tp Đà Lạt, Lâm Đồng',
      thoiGianDuKien: 8,
      loaiChuyenXe: 'veDiHCM',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Rạch Giá -> Sài Gòn',
      maHanhTrinh: 'rg-hcm',
      gioKhoiHanhHienThi: '4:15 sáng',
      gioKhoiHanhSoSanh: '04:15:00.000000',
      diemDen: 'Bến xe Miền Tây',
      giaVe: 190000,
      khoanCach: '235 km',
      diemDi: 'Bến xe Rạch Giá',
      soGhe: 16,
      dcDiemDen: '395 Kinh Đ. Vương, An Lạc, Bình Tân, Tp HCM',
      dcDiemDi: '260A Nguyễn Bỉnh Khiêm, Vĩnh Thanh, Rạch Giá, Kiên Giang',
      thoiGianDuKien: 6,
      loaiChuyenXe: 'veDiHCM',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Cà Mau -> Sài Gòn',
      maHanhTrinh: 'cm-hcm',
      gioKhoiHanhHienThi: '20:30 tối',
      gioKhoiHanhSoSanh: '20:30:00.000000',
      diemDen: 'Bến xe Miền Tây',
      giaVe: 230000,
      khoanCach: '347 km',
      diemDi: 'Bến xe Cà Mau',
      soGhe: 16,
      dcDiemDen: '395 Kinh Đ. Vương, An Lạc, Bình Tân, Tp HCM',
      dcDiemDi: 'QL 1A, phường 6, Tp Cà Mau',
      thoiGianDuKien: 9,
      loaiChuyenXe: 'veDiHCM',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
  ];

  static final List<Ticket> veDiTinhKhac = [
    Ticket(
      hanhTrinh: 'Cà Mau -> Cần Thơ',
      maHanhTrinh: 'cm-ct',
      gioKhoiHanhHienThi: '3:00 sáng',
      gioKhoiHanhSoSanh: '03:00:00.000000',
      diemDi: 'Bến xe Cà Mau',
      giaVe: 160000,
      khoanCach: '170 km',
      diemDen: 'Bến xe Cần Thơ mới',
      soGhe: 16,
      dcDiemDi: 'QL 1A, phường 6, Tp Cà Mau',
      dcDiemDen: 'QL1A, Hưng Thạnh, Cái Răng, Cần Thơ',
      thoiGianDuKien: 4,
      loaiChuyenXe: 'veDiTinhKhac',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Hà Tiên -> Bình Dương',
      maHanhTrinh: 'ht-bd',
      gioKhoiHanhHienThi: '14:30 chiều',
      gioKhoiHanhSoSanh: '14:30:00.000000',
      diemDi: 'Bến xe Hà Tiên',
      giaVe: 270000,
      khoanCach: '350 km',
      diemDen: 'Bến xe Bến Cát',
      soGhe: 16,
      dcDiemDi: 'Hẻm 51, Tô Châu, Thị trấn Hà Tiên, Kiên Giang',
      dcDiemDen: '12 H6, Thới Hoà, Bến Cát, Bình Dương',
      thoiGianDuKien: 10,
      loaiChuyenXe: 'veDiTinhKhac',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Châu Đốc -> Cà Mau',
      maHanhTrinh: 'cd-cm',
      gioKhoiHanhHienThi: '8:15 sáng',
      gioKhoiHanhSoSanh: '08:15:00.000000',
      diemDi: 'Bến xe Châu Đốc',
      giaVe: 200000,
      khoanCach: '295 km',
      diemDen: 'Bến xe Cà Mau',
      soGhe: 16,
      dcDiemDi: 'Đ. Lê Lợi, P. Châu Phú B, TP Châu Đốc, An Giang',
      dcDiemDen: 'QL 1A, phường 6, Tp Cà Mau',
      thoiGianDuKien: 7,
      loaiChuyenXe: 'veDiTinhKhac',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
    Ticket(
      hanhTrinh: 'Đà Lạt -> Nha Trang',
      maHanhTrinh: 'dl-nt',
      gioKhoiHanhHienThi: '12:30 trưa',
      gioKhoiHanhSoSanh: '12:30:00.000000',
      diemDi: 'Bến xe Đà Lạt',
      giaVe: 165000,
      khoanCach: '140 km',
      diemDen: 'Bến xe Nam Nha Trang',
      soGhe: 16,
      dcDiemDi: '1 Tô Hiến Thành, Phường 3, Tp Đà Lạt, Lâm Đồng',
      dcDiemDen: '105H đường 1A, Vĩnh Hiệp, Nha Trang, Khánh Hòa',
      thoiGianDuKien: 4,
      loaiChuyenXe: 'veDiTinhKhac',
      ngayKhoiHanhHienThi: null,
      ngayKhoiHanhSoSanh: null,
      soGheConLai: 0,
      id: null,
    ),
  ];
}
